/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "pubkey/pkg/apis/sirocco.cloud/v1alpha1"
)

// FakePubkeys implements PubkeyInterface
type FakePubkeys struct {
	Fake *FakeSiroccoV1alpha1
	ns   string
}

var pubkeysResource = schema.GroupVersionResource{Group: "sirocco.cloud", Version: "v1alpha1", Resource: "pubkeys"}

var pubkeysKind = schema.GroupVersionKind{Group: "sirocco.cloud", Version: "v1alpha1", Kind: "Pubkey"}

// Get takes name of the pubkey, and returns the corresponding pubkey object, and an error if there is any.
func (c *FakePubkeys) Get(name string, options v1.GetOptions) (result *v1alpha1.Pubkey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(pubkeysResource, c.ns, name), &v1alpha1.Pubkey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Pubkey), err
}

// List takes label and field selectors, and returns the list of Pubkeys that match those selectors.
func (c *FakePubkeys) List(opts v1.ListOptions) (result *v1alpha1.PubkeyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(pubkeysResource, pubkeysKind, c.ns, opts), &v1alpha1.PubkeyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PubkeyList{ListMeta: obj.(*v1alpha1.PubkeyList).ListMeta}
	for _, item := range obj.(*v1alpha1.PubkeyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested pubkeys.
func (c *FakePubkeys) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(pubkeysResource, c.ns, opts))

}

// Create takes the representation of a pubkey and creates it.  Returns the server's representation of the pubkey, and an error, if there is any.
func (c *FakePubkeys) Create(pubkey *v1alpha1.Pubkey) (result *v1alpha1.Pubkey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(pubkeysResource, c.ns, pubkey), &v1alpha1.Pubkey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Pubkey), err
}

// Update takes the representation of a pubkey and updates it. Returns the server's representation of the pubkey, and an error, if there is any.
func (c *FakePubkeys) Update(pubkey *v1alpha1.Pubkey) (result *v1alpha1.Pubkey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(pubkeysResource, c.ns, pubkey), &v1alpha1.Pubkey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Pubkey), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePubkeys) UpdateStatus(pubkey *v1alpha1.Pubkey) (*v1alpha1.Pubkey, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(pubkeysResource, "status", c.ns, pubkey), &v1alpha1.Pubkey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Pubkey), err
}

// Delete takes name of the pubkey and deletes it. Returns an error if one occurs.
func (c *FakePubkeys) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(pubkeysResource, c.ns, name), &v1alpha1.Pubkey{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePubkeys) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(pubkeysResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.PubkeyList{})
	return err
}

// Patch applies the patch and returns the patched pubkey.
func (c *FakePubkeys) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Pubkey, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(pubkeysResource, c.ns, name, pt, data, subresources...), &v1alpha1.Pubkey{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Pubkey), err
}
